package com.example.wearableapplication.model


/**
 * StressAnalysis
 *
 * Represents the structured result
 * generated by OpenAI stress analysis.
 *
 *
 * Flow:
 *
 * StressFeatures
 *        |
 *        |
 * PromptBuilder
 *        |
 *        |
 * OpenAI API
 *        |
 *        |
 * StressAnalysis
 *        |
 *        |
 * Dashboard UI
 *
 */
import kotlinx.serialization.Serializable


@Serializable
data class StressAnalysis(


    /**
     * Overall estimated stress score.
     *
     * Range:
     *
     * 0 - 100
     *
     *
     * Example:
     *
     * 75
     *
     */
    val stressScore: Double,



    /**
     * Human readable stress category.
     *
     * Expected values:
     *
     * Low
     * Moderate
     * High
     *
     */
    val stressLevel: String,



    /**
     * Main factors contributing
     * to the estimated stress level.
     *
     * Example:
     *
     * [
     * "High screen time",
     * "Frequent phone checking",
     * "Elevated heart rate"
     * ]
     *
     */
    val primaryFactors: List<String>,



    /**
     * Personalized recommendations.
     *
     * Example:
     *
     * [
     * "Take a 5 minute break",
     * "Walk outside",
     * "Reduce social media usage"
     * ]
     *
     */
    val recommendations: List<String>,



    /**
     * Suggested breathing activity.
     *
     * Example:
     *
     * "Box breathing for 5 minutes"
     *
     */
    val breathingExercise: String,



    /**
     * Suggested physical activity.
     *
     * Example:
     *
     * "Walk for 10 minutes"
     *
     */
    val activitySuggestion: String,



    /**
     * Advice specifically related
     * to smartphone behavior.
     *
     * Example:
     *
     * "Avoid continuous Instagram usage
     * longer than 45 minutes."
     *
     */
    val screenTimeAdvice: String,



    /**
     * Confidence score.
     *
     * Optional but useful for research.
     *
     * Example:
     *
     * 0.85
     *
     * Means:
     *
     * AI confidence = 85%
     *
     */
    val confidence: Double = 0.0,



    /**
     * Timestamp when analysis
     * was generated.
     */
    val timestamp: Long =
        System.currentTimeMillis()

)